### ISSUE TITLE
iOS Safari: Prevent scroll on input focus

### ISSUE THREAD

**Issue by jack-carling** [jack-carling/sudoku#10]
Prevent iOS from its current default scrolling behavior that centers the viewport on input field focus, forcing the user to scroll up whenever certain cells are clicked. Fix mobile viewport bug.

```css
body {
  min-height: 100vh;
  /* mobile viewport bug fix */
  min-height: -webkit-fill-available;
}
```
